function [ xNew ] = generateShape( E, m, b, r, s, tx, ty )
%GENERATESHAPE Generate shape defined by coefficient vector b
%   Input: E        ...     2nx2n Matrix of eigenvectors generated by pcaShape    
%          m        ...     2nx1 mean shape vector 
%          b        ...     kx1 vector of coefficients corresponding to the
%                           selected eigenvectors that are used to generate 
%                           the new shape (k <= 2n)
%          r        ...     rotation angle
%          s        ...     scaling factor
%          tx       ...     translation factor (x direction)
%          ty       ...     translation factor (y direction)
%   Output: xNew    ...     2xn generated shape, reshaped from 2nx1 shape vector: 
%                           xNew = m + sum_i=0:k (b(i)*E(:,i)
      
% Get number of used eigenvectors
k = length(b);

% Get number of landmarks per shape
n = size(E,1)/2;

% Calculate 2D transformation matrix
rotate = [cos(degtorad(r)) -sin(degtorad(r)) 0; sin(degtorad(r)) cos(degtorad(r)) 0; 0 0 1];
scale = [s 0 0; 0 s 0; 0 0 1];
translate = [1 0 tx; 0 1 ty; 0 0 1];
T = translate * scale * rotate;

% Generate new shape from first k eigenvectors
xNew = m + E(:,1:k)*b;
xNew = reshape(xNew, 2, n);

% Transform shape using homogeneous coords (p = (x,y,1))
xNewHom = T* [xNew;ones(1,n)] ;

% Keep 2D coords
xNew = xNewHom(1:2,:);

end

