function [  ] = plotShape( E , mean , b)
%PLOTSHAPE plots the shapes defined by b
%   blue    ...    negative multiple of lambda
%   red     ...     mean shape
%   green   ...   positive multiple of lambda
% Input:
%   E        ...     2nx2n Matrix of eigenvectors generated by pcaShape    
%   mean     ...     2nx1 mean shape vector 
%   b        ...     kx1 vector of coefficients corresponding to the
%                    selected eigenvectors that are used to generate 
%                    the new shape (k <= 2n)


% Plot the different modes
for f=1:13
    figure()
    hold on
    for i=-3:3
        shape = generateShape(E, mean, i*b(:,f));
        if i<0
            plot(shape(1,:), shape(2,:), 'b--');
        elseif i==0
            plot(shape(1,:), shape(2,:), 'r');
        elseif i>0
            plot(shape(1,:), shape(2,:), 'g--');
        end
    end
    
    lambda = diag(b.*b);
    title(sprintf('%d. mode: %.2f%% of TV',f,lambda(f)/sum(lambda)*100))
    xlabel('X');
    ylabel('Y');
    
    matlab2tikz(sprintf('figures/mode%d.tex',f),'height', '\figureheight', 'width', '\figurewidth');
    close all
end
end
